### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by abithanjaleepv** [maups/covid19-satellite-analysis#3]
I have installed all your requirements.
But, I'm getting an error while running  ./download_models.sh
![Screenshot from 2022-04-23 21-15-52](https://user-images.githubusercontent.com/102481127/164890678-9f6c4ef9-fb12-453b-b0f2-eb57fefb2c14.png)

How to run your repository ?
Kindly, share your screenshot.

**Comment by maups** [comment]
You have to install curl before running this script:

$ sudo apt install curl
