### ISSUE TITLE
Error show_regions.py file

### ISSUE THREAD

**Issue by abithanjaleepv** [maups/covid19-satellite-analysis#4]
![Screenshot from 2022-04-26 16-46-26](https://user-images.githubusercontent.com/102481127/165231255-efd10355-1da8-453a-8d77-0160e7585083.png)
![Screenshot from 2022-04-26 16-46-52](https://user-images.githubusercontent.com/102481127/165231262-726e8c2c-3065-4715-85bb-7e7c7367e1be.png)
I'm getting an error these commands sir.

**Comment by maups** [comment]
You have to install the requirements before running it: https://github.com/maups/covid19-satellite-analysis/blob/master/requirements.txt
